# OpenCV Surveillance System - Integration Configuration
# This file configures all smart home integrations

# =============================================================================
# HOME ASSISTANT INTEGRATION
# =============================================================================
home_assistant:
  enabled: true
  
  # MQTT Configuration for Home Assistant Discovery
  mqtt:
    host: localhost
    port: 1883
    username: homeassistant
    password: your_mqtt_password
    
    # Discovery and state topics
    discovery_prefix: homeassistant
    state_prefix: opencv_surveillance
    
    # TLS/SSL (optional)
    use_tls: false
    ca_certs: null
    certfile: null
    keyfile: null
  
  # Auto-discovery settings
  discovery:
    enabled: true
    # Automatically register cameras as they come online
    auto_register_cameras: true
    # Create motion sensors for each camera
    create_motion_sensors: true
    # Publish system sensors (CPU, memory, storage)
    publish_system_sensors: true
    system_sensor_interval: 60  # seconds

# =============================================================================
# HOMEKIT INTEGRATION
# =============================================================================
homekit:
  enabled: false
  
  # Bridge configuration
  bridge_name: OpenCV Surveillance
  pincode: "123-45-678"  # Must be in format XXX-XX-XXX
  port: 51826
  
  # Persistence
  persist_file: ./config/homekit_state.json
  
  # Camera settings
  cameras:
    # Video quality presets
    video_quality: high  # low, medium, high
    snapshot_width: 1920
    snapshot_height: 1080
    
    # Enable doorbell functionality for specific cameras
    doorbells:
      - camera_1  # Front door camera
  
  # Features
  features:
    motion_detection: true
    audio_streaming: true
    video_recording: true  # HomeKit Secure Video

# =============================================================================
# GOOGLE NEST INTEGRATION
# =============================================================================
nest:
  enabled: false
  
  # Google Cloud Project Configuration
  # Get these from Google Cloud Console after enabling SDM API
  project_id: your-google-project-id
  client_id: your-client-id.apps.googleusercontent.com
  client_secret: your-client-secret
  redirect_uri: http://localhost:8080/oauth/callback
  
  # OAuth credentials storage
  credentials_file: ./config/nest_credentials.json
  
  # Pub/Sub configuration for events
  pubsub:
    enabled: true
    topic: nest-events
    subscription: opencv-surveillance-events
  
  # Features
  features:
    # Import Nest camera feeds
    import_nest_cameras: false
    # Send notifications to Nest Hub displays
    send_notifications: true
    # Sync events with Nest
    event_sync: true

# =============================================================================
# MQTT INTEGRATION (Generic)
# =============================================================================
mqtt:
  enabled: true
  
  # Broker configuration
  broker:
    host: localhost
    port: 1883
    username: surveillance
    password: your_mqtt_password
    client_id: opencv_surveillance
    keepalive: 60
    clean_session: true
  
  # TLS/SSL
  tls:
    enabled: false
    ca_certs: /path/to/ca.crt
    certfile: /path/to/client.crt
    keyfile: /path/to/client.key
  
  # Topic configuration
  topics:
    base_topic: surveillance
    status_topic: surveillance/status
    command_topic: surveillance/command
  
  # Publishing
  publish:
    # Quality of Service (0, 1, 2)
    qos: 1
    # Retain messages
    retain: true
    # Events to publish
    events:
      - motion_detected
      - face_detected
      - recording_started
      - recording_stopped
      - camera_online
      - camera_offline
  
  # System metrics publishing
  metrics:
    enabled: true
    interval: 30  # seconds
    publish_cpu: true
    publish_memory: true
    publish_disk: true
    publish_camera_count: true

# =============================================================================
# WEBHOOK SYSTEM
# =============================================================================
webhooks:
  enabled: true
  
  # Webhook database
  database_file: ./config/webhooks.json
  
  # Global retry settings (can be overridden per webhook)
  defaults:
    max_retries: 3
    retry_delay: 5  # seconds
    timeout: 10  # seconds
  
  # Delivery history
  history:
    enabled: true
    max_entries: 1000  # Keep last N deliveries
    cleanup_interval: 3600  # Clean up old entries every hour
  
  # Pre-configured webhooks
  registered:
    - id: discord_notifications
      url: https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN
      events:
        - motion_detected
        - face_detected
      active: true
      camera_ids: null  # All cameras
      headers:
        Content-Type: application/json
    
    - id: slack_alerts
      url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
      events:
        - system_alert
        - camera_offline
      active: false
      secret: your_secret_key
      max_retries: 5

# =============================================================================
# INTEGRATION MANAGER SETTINGS
# =============================================================================
integration_manager:
  # Enable/disable all integrations
  enabled: true
  
  # Event queue settings
  event_queue:
    max_size: 1000
    # Process events in batches
    batch_size: 10
    batch_interval: 1  # seconds
  
  # Error handling
  error_handling:
    # Continue on integration errors
    continue_on_error: true
    # Log failed events
    log_failures: true
    # Retry failed events
    retry_failed_events: true
    max_event_retries: 3
  
  # Performance
  performance:
    # Maximum concurrent webhook deliveries
    max_concurrent_webhooks: 10
    # Event processing threads
    worker_threads: 4

# =============================================================================
# CUSTOM INTEGRATIONS
# =============================================================================
custom_integrations:
  # Add custom integration scripts
  scripts:
    - name: custom_integration
      path: ./integrations/custom/my_integration.py
      enabled: false
      config:
        # Custom configuration for your integration
        api_key: your_api_key
        endpoint: https://api.example.com

# =============================================================================
# LOGGING
# =============================================================================
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Integration-specific logging
  integrations:
    home_assistant: INFO
    homekit: INFO
    nest: INFO
    mqtt: INFO
    webhooks: INFO
  
  # Log file
  file:
    enabled: true
    path: ./logs/integrations.log
    max_size: 10485760  # 10MB
    backup_count: 5
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"