name: Build and Push to Docker Hub

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  # TODO: Replace with your Docker Hub username
  DOCKER_USERNAME: your-dockerhub-username  # <- CHANGE THIS
  IMAGE_NAME: openeye-surveillance

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        # TODO: Add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN to GitHub Secrets
        # Go to: Settings > Secrets and variables > Actions > New repository secret
        # Name: DOCKERHUB_USERNAME  Value: your Docker Hub username
        # Name: DOCKERHUB_TOKEN     Value: your Docker Hub access token
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # <- ADD TO GITHUB SECRETS
        password: ${{ secrets.DOCKERHUB_TOKEN }}     # <- ADD TO GITHUB SECRETS
    
    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILD_DATE=${{ github.event.repository.updated_at }}
          VCS_REF=${{ github.sha }}
          VERSION=${{ steps.meta.outputs.version }}
    
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      if: github.event_name != 'pull_request'
      with:
        # TODO: Add to GitHub Secrets
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # <- ADD TO GITHUB SECRETS
        password: ${{ secrets.DOCKERHUB_TOKEN }}     # <- ADD TO GITHUB SECRETS
        repository: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        short-description: "OpenEye - OpenCV-powered surveillance system with face recognition"
        readme-filepath: ./README.md

  verify-image:
    name: Verify Docker Image
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name != 'pull_request'
    
    steps:
    - name: Pull and test image
      run: |
        docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        docker run --rm ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest python -c "import cv2, numpy; print('✅ Dependencies OK')"
